name: Issue Labeler

on:
  issue:
    types: [opened, edited]

job:
  labeling:
    runs-on: ubuntu-latest
    steps:
      - uses: github/issue-labeler@v2.5
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          configuration-path: .github/issue-labeler.yml
          not-before: 2022-11-30T09:00:00Z
          enable-versioned-regex: 0
          include-title: 1
