name: Lighthouse Test

on: workflow_dispatch

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - name: Audit live URL
      uses: jakejarvis/lighthouse-action@master
      with:
        url: 'https://www.naver.com'
