name: Test-Action

on:
  pull_request:
    branches:
      - main
    types: [opened, reopened, edited, synchronize, ready_for_review]
jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - name: test echo step
        run: echo "This is test"
      - name: echo base branch
        run: echo "$GITHUB_BASE_REF"
      - name: echo head branch
        run: ehco "$GITHUB_HEAD_REF"
      # - name: sleep step
      #   run: sleep 3m
      - name: echo complete status
        run: echo "Complete"
