name: Test-Action

on:
  pull_request:
    branches:
      - main
    types: [opened, reopened, edited, synchronize, ready_for_review]
jobs:
  test-action:
    # if: github.head_ref == 'develop'
    runs-on: ubuntu-latest
    steps:
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            src:
              - 'webpack/**/*'
      - name: path filter test
        run: echo "Path filter test"
        if: steps.changes.outputs.src == 'true'
      - name: test echo step
        run: echo "This is test"
      - name: echo base branch
        run: echo "$GITHUB_BASE_REF"
      - name: echo head branch
        run: echo "$GITHUB_HEAD_REF"
      - name: echo trigger evnet
        run: echo "${{ github.event.action }}"
      - name: echo event.changes.base
        run: echo "${{ github.event.changes.base }}"
        if: github.event.action == 'edited' && github.event.changes.base
      - name: ehco github.run_id
        run: echo "${{ github.run_id }}"
      - name: ehco github.run_number
        run: echo "${{ github.run_number }}"
      - name: ehco github.ref
        run: echo "${{ github.ref }}"
      - name: echo PR number
        run: echo "${{ github.event.number }}"
      # - name: sleep step
      #   run: sleep 3m
      - name: echo complete status
        run: echo "Complete"
