name: Test-Action

on:
  pull_request:
    branches:
      - main
    types: [opened, reopened, edited, synchronize, ready_for_review]
jobs:
  test-action:
    # if: ${{ !(github.event.changes.title || github.event.changes.body) }}
    runs-on: ubuntu-latest
    steps:
      - uses: n1hility/cancel-previous-runs@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          workflow: Test-Action.yml
      - name: test echo step
        run: echo "This is test"
      - name: echo base branch
        run: echo "$GITHUB_BASE_REF"
      - name: echo head branch
        run: echo "$GITHUB_HEAD_REF"
      - name: echo trigger evnet
        run: echo "${{ github.event.action }}"
      - name: echo event.changes.base
        run: echo "${{ github.event.changes.base }}"
        if: github.event.action == 'edited' && github.event.changes.base
      - name: sleep step
        run: sleep 3m
      - name: echo complete status
        run: echo "Complete"
