name: Test-Action

on:
  pull_request:
    branches:
      - main
    types: [opened, reopened, edited, synchronize, ready_for_review]
jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - name: test echo step
        run: echo "This is test"
      - name: sleep step
        run: sleep 3m
